### ISSUE TITLE
bias calculation

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/pytesmo#138]
Hey! Bias is currently np.mean(observations) - np.mean(predictions), but should be the other way around, right? @iteubner also mentioned this some time ago.

**Comment by sebhahn** [comment]
Well, it's always a matter of how you pass the arguments to the bias function. In the paper of [Janssen et al.](https://www.sciencedirect.com/science/article/pii/0304380095000849) it is defined as `predictions - observations`.

Anyway, I think it is more plausible with `observations - reference`

**Comment by wpreimes** [comment]
So you would keep `predictions - observations`? Why not stick with the definition from the paper?

**Comment by sebhahn** [comment]
I think the documentation should be updated and make it clear, because in many cases we all work with "observations" only and not with model data.

In case someone has many data sets (x1, x2, x3, etc.) and a reference data set (y) (no matter if xi or y are model data, observations, etc.) it should be clear that it is always xi - y. And than the arguments should have a meaningful documentation.

**Comment by wpreimes** [comment]
So would make sense do give them more general names like `can` (candidate) or `src`, and `ref` (reference) and define bias as `mean(can)`- `mean(ref)`? Would you do this also for the other metrics?

**Comment by wpreimes** [comment]
sure, but I'd suggest having consistent names, even if it doesn't make a difference computationally. If you want, I can updated the names and make a PR with the suggested changes.

**Comment by cpaulik** [comment]
I would not like to switch the argument order since this would lead to all existing code suddenly producing different results.

As far as I've seen by quickly going through the code bias is the only metric we have where the argument order matters.

About the documentation. I've actually liked the way it was before `o` and `p` where introduced where we just had `x` and `y` and the calling function has to decide in which direction the bias is interesting based on the application. E.g. the validation framework [call the bias function with `bias(ref, other)`](https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/validation_framework/metric_calculators.py#L116).

**Comment by iteubner** [comment]
You are right, it is only a matter of how the function is called. But I still think it would be more intuitive for someone who takes a look at the code to see the reference (usually called observations) as the second argument in the subtraction, i.e. mean(p)-mean(o). 

Maybe I am missing something, but if one would exchange both the order of the arguments and the order of the subtraction it should stay the same for existing code, right?

Alternatively, one could maybe state that the predictions are the reference.

**Comment by cpaulik** [comment]
I would just keep the bias function very simple. Call them `x` and `y` and just state in the documentation that the bias is `mean(x) -mean(y)`. Finding the right word for `reference`, `observations`, `estimator` and probably other words that could mean the same thing is not worth it.

I would however be open to the argument that the validation framework calls the bias function in the wrong order.

**Comment by sebhahn** [comment]
Well, bias is not so much of an issue and the naming doesn't matter, however, some metrics have been defined with specific names (`observations`, `predictions`) and there we should use them.

**Comment by wpreimes** [comment]
@sebhahn Which ones? I assume:
- `index_of_agreement` and `nash_sutcliffe` 

So we could keep the current names for them and switch to more generic ones for other, general metrics (which are not for model validation only as the current naming pretends), where the input order does not affect the output anyways (just checked) to something like `x` and `y`:
- `aad`, `mad`, `RSS`, `rmsd`, `nrmsd`, `ubrmsd`, `mse`, `pearsonr`, `spearmanr`, `kendalltau`

I'd point out for the bias function that the input order matters in the documentation and that we, as Christoph said, calculate `mean(x)-mean(y)` with `x` as the first and `y` as the second arg.

**Comment by sebhahn** [comment]
sound ok for me

**Comment by wpreimes** [comment]
I think I found another bug related to this: In the `_to_namedtuple()` function the dataset names get mixed up (only has an affect on bias).

See this example:
```python
from pytesmo import metrics, df_metrics
df = pd.DataFrame(index=pd.date_range('2000-01-01', '2000-12-31', freq='D'),
                      data={'ds0':np.repeat(0, 366) , 'ds1':np.repeat(1, 366)})
```
```
>>> print(metrics.bias(df.iloc[:, 0].values, df.iloc[:, 1].values))
-1.0   --> as expected
>>> print(df_metrics.bias(df)) # current implementation
bias(ds0_and_ds1=1.0)  --> different to above
```
I wonder if there was some intention behind this, otherwise I will fix it in the next PR (which contains changes to how metrics are applied to dataframes etc.)

**Comment by sebhahn** [comment]
@wpreimes can we close this issue?

**Comment by wpreimes** [comment]
I think so
