### ISSUE TITLE
SyntaxError when building pytesmo on python 3.6

### ISSUE THREAD

**Issue by awst-baum** [TUW-GEO/pytesmo#148]
Sorry to ask such a stupid question but could one of you alleviate my python ignorance?

In the latest [Travis build](https://travis-ci.org/TUW-GEO/pytesmo/jobs/412534480) for python 3.6, installing pytesmo with `python setup.py install` generates a SyntaxError: `SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Variable 'jobs' is not defined!")?`

And yet the tests complete without errors. For a Java person, this doesn't make any sense at all.

**Comment by awst-baum** [comment]
I'm happy to insert a few brackets here and there and create a pull request. I just have no clue what's going on with the travis tests (why they don't fail if compilation yields a syntax error).

**Comment by cpaulik** [comment]
The tests don't fail because we never call the `start_validation.py` script in any test. It was mainly intended as an example for people trying to run the validation framework in parallel.

It is also an old example. Nowadays I would no longer use ipyparallel for parallel execution of the validation framework but either `dask` or `celery`

So feel free to add the brackets but I do not consider it very important

**Comment by awst-baum** [comment]
Aaah, OK, thanks for the explanation. I would have expected an installation to break/fail on a compile error but apparently that's not what happens.

I've added the brackets because I think error-free compilation is more newbie friendly (if you haven't got a feel yet for which errors you can ignore and which ones you have to address).

**Comment by cpaulik** [comment]
> Aaah, OK, thanks for the explanation. I would have expected an installation to break/fail on a compile error but apparently that's not what happens.
I'm actually surprised that this is checked when a package is installed. Normally python programs fail at import time if there is a SyntaxError.
