### ISSUE TITLE
default number of bins in pytesmo.scaling.cdf_match() very high

### ISSUE THREAD

**Issue by Lmoesinger** [TUW-GEO/pytesmo#175]
Minor nitpick: The default value of 100 bins for `pytesmo.scaling.cdf_match()` is very high. This will lead a) to overfitting and b) the first and last bin, which are the most important ones as they are used to extrapolate beyond the value range of the input data, will be very unstable if they are based on only a few observations. 100 bins is a reasonable value if you have more than 20000 observations, but im gonna guess that most users have way less. Also it is better to err on the smaller side as it will give bad but stable fit rather than a bad but also unstable fit.

Solution: change it to from 100 down to about 5.

**Comment by wpreimes** [comment]
I agree, I will change that

**Comment by wpreimes** [comment]
or, you know, open a PR!
I'm not even maintainer here 😄

**Comment by Lmoesinger** [comment]
A PR for a change of one number seems a bit an overkill XD

**Comment by wpreimes** [comment]
I'm sure there are more things you can fix 😄 
but I can change that number of course

**Comment by wpreimes** [comment]
It is actually not that trivial, because the tests depend on the default value and [other functions](https://github.com/TUW-GEO/pytesmo/blob/00cf9f97a58ed51cbb71d458357961f3a7526183/pytesmo/scaling.py#L83) that call scaling method don't allow passing arguments to override the (new) default value. And the [spline order](https://github.com/TUW-GEO/pytesmo/blob/00cf9f97a58ed51cbb71d458357961f3a7526183/pytesmo/scaling.py#L353) also depends on the number of percentiles. So we should change this in the next main release instead together with a lot of other things.

**Comment by Lmoesinger** [comment]
ok, this is a lot more complicated than i anticipated ;)

**Comment by s-scherrer** [comment]
closed via #207
