### ISSUE TITLE
No module named 'pytesmo.io' when import pytesmo.io.ismn.interface

### ISSUE THREAD

**Issue by xushanthu-2014** [TUW-GEO/pytesmo#192]
hello
I am trying to use pytesmo to validate the ismn dataset. However the script/demo got from your website (https://pytesmo.readthedocs.io/en/latest/examples.html#examples-page) didn't work when I tried this:

from pytesmo.io.ismn.interface import ISMN_Interface

just got:
Traceback (most recent call last):

  File "<ipython-input-67-ceea508d4476>", line 1, in <module>
    from pytesmo.io.ismn.interface import ISMN_Interface

ModuleNotFoundError: No module named 'pytesmo.io'

it seems that pytesmo only has 'df_metrics', 'metrics', 'pkg_resources', 'scaling', 'temporal_matching', 'utils' and 'validation_framework'. And there is nothing related to 'pytesmo.io.ismn.interface'. 
and I used 'pip install pytesmo' in the terminal of my Mac. My python version is 3.7 (anaconda). I am quite new to the pytesmo, so could you please help with this issue?

**Comment by wpreimes** [comment]
Hi,
looks like the documentation is outdated. We have moved the ``io`` modules to separate github packages some time ago.
Instead of ``from pytesmo.io.ismn.interface import ISMN_Interface`` you can use ``from ismn.interface import ISMN_interface`` (after ``pip install ismn`` see package: https://github.com/TUW-GEO/ismn)

**Comment by wpreimes** [comment]
I have updated the docs (will be included in the next build), thanks for pointing it out. I'm closing this issue for now, but you can re-open it if you find any other errors.
