### ISSUE TITLE
how to read the Fran_aqui and cosmos data?

### ISSUE THREAD

**Issue by xushanthu-2014** [TUW-GEO/pytesmo#193]
Hi thanks for your help!
And I downloaded the data within southeastern France which contains sites from cosmos, fr_aqui and sosmania. They are all contained in the ismn dataset.
When I tried the data listed in your demo (https://pytesmo.readthedocs.io/en/latest/examples.html#examples-page), I can successfully read the data under the directory of 'SOSMANIA', but not of 'FR_Aqui' or 'COSMOS'. So how can I do that?

here is the directory of my data downloaded from https://www.geo.tuwien.ac.at/insitu/data_viewer/?user_id=7565&session=2mj3vrhpg1ho06zj3lfizaz1lkobexhd# (ceop format):

Data_seperate_files_19960101_20191231_7565_Qqnl_20200622 xushan$ pwd
/Users/xushan/research/TUD/surfex/southfr/Data_seperate_files_19960101_20191231_7565_Qqnl_20200622
Data_seperate_files_19960101_20191231_7565_Qqnl_20200622 xushan$ ls
COSMOS					Readme.txt
FR_Aqui					SMOSMANIA
ISMN_qualityflags_description.txt	python_metadata
Metadata.xml

thanks and hope for your early reply!

**Comment by sebhahn** [comment]
I saw your previous issue (https://github.com/TUW-GEO/pytesmo/issues/192), but I guess you are now using the [ismn package](https://github.com/TUW-GEO/ismn) for reading the in-situ data, right? If this is the case, please re-post the issue in the [ismn package](https://github.com/TUW-GEO/ismn), because it needs to be documented/solved there. Thanks!

**Comment by wpreimes** [comment]
This was resolved in https://github.com/TUW-GEO/ismn/issues/25
