### ISSUE TITLE
tcol_snr metric calculation?

### ISSUE THREAD

**Issue by ninadel** [TUW-GEO/pytesmo#200]
https://github.com/TUW-GEO/pytesmo/blob/a49e70986cb9450a8d441c5334e3153da0f54e3b/src/pytesmo/metrics.py#L331

Hi, I am looking at the formula above the linked calculation. I think there might be a mistake where there's a ** -1. Perhaps it was intended to be a * -1 instead?

**Comment by sebhahn** [comment]
@alegrub88 could you verify this?
@cpaulik testing of tcol has been performed, right?

**Comment by cpaulik** [comment]
We do have a test that checks the SNR based on a synthetic dataset. Other than that I think I took the code from @alegrub88 back then and put it into a documented function back in https://github.com/TUW-GEO/pytesmo/pull/42

**Comment by cpaulik** [comment]
Looking at the code in https://github.com/alexgruber/validation_good_practice/blob/master/ancillary/metrics.py#L179-L181 it is definitely different

It might also be that @alexgruber is the correct handle for @alegrub88

**Comment by wpreimes** [comment]
I compared to the paper. `log10(1/n) = -1 * log_10(n)`. As (other than described in the paper) there is no multiplication of the (scaled) SNR with `*-1`, but before log scaling, I think the implementation here is correct (but a bit confusing).
Compare to formula (14) in [DOI: 10.1016/j.jag.2015.09.002](https://www.sciencedirect.com/science/article/abs/pii/S0303243415300258?via%3Dihub)

**Comment by wpreimes** [comment]
but it might make sense in some cases to use the absolute value (as [here)](https://github.com/alexgruber/validation_good_practice/blob/6dd24ee1a6cbf32385582b96cb9f08d93e57c49b/ancillary/metrics.py#L179) ?

**Comment by sebhahn** [comment]
@wpreimes maybe, b

**Comment by wpreimes** [comment]
Sounds like you wanted to say "..., but" ;)

**Comment by KUL-RSDA** [comment]
The equation with a ** (-1) is correct.

I think the confusion is because the SNR in Eq. 14 in the [jag paper](https://www.sciencedirect.com/science/article/abs/pii/S0303243415300258) is in decibel units, i.e. -10 log (a), but the equation in pytesmo calculates the SNR in linear units.

As @wpreimes correctly pointed out, log(a/b) = log(a) - log(b). Hence, the logarithmic -log(a) = log(1/a) is calculated linearly as a ** (-1) 

And yes, @alexgruber is my correct GitHub account.

**Comment by alexgruber** [comment]
My bad, I was logged in with the wrong GitHub account. I think you get it.

**Comment by alexgruber** [comment]
Oh, and @wpreimes, the calculation of absolute values is indeed unrelated to this and serves to avoid negative error variance estimates that can occur due to statistical sampling noise. For more details, see Sec. 4.1 in [this paper](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017WR021277)

**Comment by wpreimes** [comment]
@alexgruber Great, thanks for clarifying
